# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0.json

version: 2

updates:
-
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
        interval: "daily"
-
    package-ecosystem: "composer"
    directory: "/"
    schedule:
        interval: "daily"
    #allow:
    #-
    #    dependency-name: "*"
    #    dependency-type: "production"
-
    package-ecosystem: "npm"
    directory: "/"
    schedule:
        interval: "daily"
    #allow:
    #-
    #    dependency-name: "*"
    #    dependency-type: "production"
-
    package-ecosystem: "docker"
    directory: "/"
    schedule:
        interval: "daily"
