# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: "Commits"

on:  # yamllint disable-line rule:truthy
    pull_request: null
# Add [skip ci] to commit message to skip CI.

permissions:
    contents: "read"

concurrency:
    group: "${{ github.workflow }}-${{ github.ref }}"
    cancel-in-progress: true

jobs:
    commit_authors:
        name: "Commit authors"
        runs-on: "ubuntu-22.04"
        timeout-minutes: 2
        steps:
        -
            name: "Checkout repository"
            uses: "actions/checkout@v3"
            with:
                fetch-depth: 0
        -
            name: "Query commit email addresses from GitHub API"
            run: |
                Check_author() {
                    local AUTHOR="$1"
                    local GITHUB_API_URL="https://api.github.com/search/users"
                    echo "Checking ${AUTHOR} ..."
                    curl --silent --get --data-urlencode "q=type:user in:email ${AUTHOR}" "${GITHUB_API_URL}" \
                        | grep --fixed-strings --line-regexp '  "total_count": 1,'
                }
                git show --no-patch --pretty="format:%ae" "${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}" \
                    | sort --unique \
                    | while read -r AUTHOR; do Check_author "${AUTHOR}"; done
